// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OffersColumns holds the columns for the "offers" table.
	OffersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "master_id", Type: field.TypeUUID},
		{Name: "order_id", Type: field.TypeUUID},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "accepted", "cancelled", "rejected"}, Default: "active"},
		{Name: "price", Type: field.TypeFloat32, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OffersTable holds the schema information for the "offers" table.
	OffersTable = &schema.Table{
		Name:       "offers",
		Columns:    OffersColumns,
		PrimaryKey: []*schema.Column{OffersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OffersTable,
	}
)

func init() {
}
