// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ostap00034/course-work-backend-offer-service/ent/offer"
	"github.com/google/uuid"
)

// OfferCreate is the builder for creating a Offer entity.
type OfferCreate struct {
	config
	mutation *OfferMutation
	hooks    []Hook
}

// SetMasterID sets the "master_id" field.
func (oc *OfferCreate) SetMasterID(u uuid.UUID) *OfferCreate {
	oc.mutation.SetMasterID(u)
	return oc
}

// SetOrderID sets the "order_id" field.
func (oc *OfferCreate) SetOrderID(u uuid.UUID) *OfferCreate {
	oc.mutation.SetOrderID(u)
	return oc
}

// SetStatus sets the "status" field.
func (oc *OfferCreate) SetStatus(o offer.Status) *OfferCreate {
	oc.mutation.SetStatus(o)
	return oc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (oc *OfferCreate) SetNillableStatus(o *offer.Status) *OfferCreate {
	if o != nil {
		oc.SetStatus(*o)
	}
	return oc
}

// SetPrice sets the "price" field.
func (oc *OfferCreate) SetPrice(f float32) *OfferCreate {
	oc.mutation.SetPrice(f)
	return oc
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (oc *OfferCreate) SetNillablePrice(f *float32) *OfferCreate {
	if f != nil {
		oc.SetPrice(*f)
	}
	return oc
}

// SetCreatedAt sets the "created_at" field.
func (oc *OfferCreate) SetCreatedAt(t time.Time) *OfferCreate {
	oc.mutation.SetCreatedAt(t)
	return oc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (oc *OfferCreate) SetNillableCreatedAt(t *time.Time) *OfferCreate {
	if t != nil {
		oc.SetCreatedAt(*t)
	}
	return oc
}

// SetUpdatedAt sets the "updated_at" field.
func (oc *OfferCreate) SetUpdatedAt(t time.Time) *OfferCreate {
	oc.mutation.SetUpdatedAt(t)
	return oc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (oc *OfferCreate) SetNillableUpdatedAt(t *time.Time) *OfferCreate {
	if t != nil {
		oc.SetUpdatedAt(*t)
	}
	return oc
}

// SetID sets the "id" field.
func (oc *OfferCreate) SetID(u uuid.UUID) *OfferCreate {
	oc.mutation.SetID(u)
	return oc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (oc *OfferCreate) SetNillableID(u *uuid.UUID) *OfferCreate {
	if u != nil {
		oc.SetID(*u)
	}
	return oc
}

// Mutation returns the OfferMutation object of the builder.
func (oc *OfferCreate) Mutation() *OfferMutation {
	return oc.mutation
}

// Save creates the Offer in the database.
func (oc *OfferCreate) Save(ctx context.Context) (*Offer, error) {
	oc.defaults()
	return withHooks(ctx, oc.sqlSave, oc.mutation, oc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (oc *OfferCreate) SaveX(ctx context.Context) *Offer {
	v, err := oc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oc *OfferCreate) Exec(ctx context.Context) error {
	_, err := oc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oc *OfferCreate) ExecX(ctx context.Context) {
	if err := oc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (oc *OfferCreate) defaults() {
	if _, ok := oc.mutation.Status(); !ok {
		v := offer.DefaultStatus
		oc.mutation.SetStatus(v)
	}
	if _, ok := oc.mutation.Price(); !ok {
		v := offer.DefaultPrice
		oc.mutation.SetPrice(v)
	}
	if _, ok := oc.mutation.CreatedAt(); !ok {
		v := offer.DefaultCreatedAt()
		oc.mutation.SetCreatedAt(v)
	}
	if _, ok := oc.mutation.UpdatedAt(); !ok {
		v := offer.DefaultUpdatedAt()
		oc.mutation.SetUpdatedAt(v)
	}
	if _, ok := oc.mutation.ID(); !ok {
		v := offer.DefaultID()
		oc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oc *OfferCreate) check() error {
	if _, ok := oc.mutation.MasterID(); !ok {
		return &ValidationError{Name: "master_id", err: errors.New(`ent: missing required field "Offer.master_id"`)}
	}
	if _, ok := oc.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "Offer.order_id"`)}
	}
	if _, ok := oc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Offer.status"`)}
	}
	if v, ok := oc.mutation.Status(); ok {
		if err := offer.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Offer.status": %w`, err)}
		}
	}
	if _, ok := oc.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Offer.price"`)}
	}
	if _, ok := oc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Offer.created_at"`)}
	}
	if _, ok := oc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Offer.updated_at"`)}
	}
	return nil
}

func (oc *OfferCreate) sqlSave(ctx context.Context) (*Offer, error) {
	if err := oc.check(); err != nil {
		return nil, err
	}
	_node, _spec := oc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	oc.mutation.id = &_node.ID
	oc.mutation.done = true
	return _node, nil
}

func (oc *OfferCreate) createSpec() (*Offer, *sqlgraph.CreateSpec) {
	var (
		_node = &Offer{config: oc.config}
		_spec = sqlgraph.NewCreateSpec(offer.Table, sqlgraph.NewFieldSpec(offer.FieldID, field.TypeUUID))
	)
	if id, ok := oc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := oc.mutation.MasterID(); ok {
		_spec.SetField(offer.FieldMasterID, field.TypeUUID, value)
		_node.MasterID = value
	}
	if value, ok := oc.mutation.OrderID(); ok {
		_spec.SetField(offer.FieldOrderID, field.TypeUUID, value)
		_node.OrderID = value
	}
	if value, ok := oc.mutation.Status(); ok {
		_spec.SetField(offer.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := oc.mutation.Price(); ok {
		_spec.SetField(offer.FieldPrice, field.TypeFloat32, value)
		_node.Price = value
	}
	if value, ok := oc.mutation.CreatedAt(); ok {
		_spec.SetField(offer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := oc.mutation.UpdatedAt(); ok {
		_spec.SetField(offer.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OfferCreateBulk is the builder for creating many Offer entities in bulk.
type OfferCreateBulk struct {
	config
	err      error
	builders []*OfferCreate
}

// Save creates the Offer entities in the database.
func (ocb *OfferCreateBulk) Save(ctx context.Context) ([]*Offer, error) {
	if ocb.err != nil {
		return nil, ocb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ocb.builders))
	nodes := make([]*Offer, len(ocb.builders))
	mutators := make([]Mutator, len(ocb.builders))
	for i := range ocb.builders {
		func(i int, root context.Context) {
			builder := ocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OfferMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ocb *OfferCreateBulk) SaveX(ctx context.Context) []*Offer {
	v, err := ocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ocb *OfferCreateBulk) Exec(ctx context.Context) error {
	_, err := ocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocb *OfferCreateBulk) ExecX(ctx context.Context) {
	if err := ocb.Exec(ctx); err != nil {
		panic(err)
	}
}
